-- CREATE THE DATABASE
CREATE DATABASE IF NOT EXISTS MUSEUM_VIEW_HOTEL;

-- CREATE INDIVIDUAL TABLES
-- Users Table
CREATE TABLE IF NOT EXISTS USERS();

-- Reception Table
CREATE TABLE IF NOT EXISTS RECEPTION();

-- Admin Table
CREATE TABLE IF NOT EXISTS ADMIN(
    ADMIN_ID VARCHAR(32) PRIMARY KEY,
    USER_NAME VARCHAR(32) UNIQUE,
    PASSWORD VARCHAR(128),

);

-- Store Table
CREATE TABLE IF NOT EXISTS STORE();